### ISSUE TITLE
ErrorHandlerInterceptor Undefined array key "driver"

### ISSUE THREAD

**Issue by gam6itko** [spiral/roadrunner-bridge#82]
### Description

After upgrading to v3.0 I've got error when push job to sync connection

```
Undefined array key "driver" in vendor/spiral/framework/src/Queue/src/Interceptor/Consume/ErrorHandlerInterceptor.php:27
```

### How To Reproduce

https://github.com/spiral/app/compare/master...gam6itko:app:rr_bridje_3

### Additional Info

| Q                | A
|------------------| ---
| Package Version  | 3.0 
| PHP version      | 8.1  
| Operating system | Linux

**Comment by msmakouz** [comment]
@gam6itko `Spiral\Queue\Interceptor\Consume\ErrorHandlerInterceptor` is a **consume**, not a **push** interceptor. It must be added to the **consume** array in the configuration file.
This interceptor allows you to handle exceptions that are thrown when a job is executing.
